### ISSUE TITLE
literal render JSX not working

### ISSUE THREAD

**Issue by kethan** [WebReflection/hooked-elements#3]
Hi if I use hooks in a literal render with JSX it's breaking.

https://codepen.io/kethan-the-selector/pen/PomRvrj?editors=0001

**Comment by WebReflection** [comment]
this works for me?

```js
import { render } from '//cdn.skypack.dev/uhtml/jsx';
import { define, useState } from "https://unpkg.com/hooked-elements?module";

define("func-counter", (element) => {
  const [count, update] = useState(0);
  const [children] = useState([...element.childNodes]);

  render(
    element,
    <div>
      <div>{children}</div>
      <button class="large btn" onclick={() => update(count - 1)}>
        -
      </button>
      <span class="large value"> {count} </span>
      <button class="large btn" onclick={() => update(count + 1)}>
        +
      </button>
    </div>
  );
});
```

**Comment by kethan** [comment]
> this works for me?
> 
> ```js
> import { render } from '//cdn.skypack.dev/uhtml/jsx';
> import { define, useState } from "https://unpkg.com/hooked-elements?module";
> 
> define("func-counter", (element) => {
>   const [count, update] = useState(0);
>   const [children] = useState([...element.childNodes]);
> 
>   render(
>     element,
>     <div>
>       <div>{children}</div>
>       <button class="large btn" onclick={() => update(count - 1)}>
>         -
>       </button>
>       <span class="large value"> {count} </span>
>       <button class="large btn" onclick={() => update(count + 1)}>
>         +
>       </button>
>     </div>
>   );
> });
> ```

if I use a literal type of object how to call render function? I would like to use init function etc.

And why if call the {children} twice in the code it renders only once?

**Comment by WebReflection** [comment]
> And why if call the {children} twice in the code it renders only once?

a node cannot exist twice in the DOM ... it exists only where you put it. If you want it twice, you need to clone it? this is how DOM works, here you're referencing `childNodes`, no magic whatsoever, and no vDOM neither, so ... clone nodes you want to repeat in your template, and clone these once, for better performance on each update (same ref, no changes).

**Comment by kethan** [comment]
> > And why if call the {children} twice in the code it renders only once?
> 
> a node cannot exist twice in the DOM ... it exists only where you put it. If you want it twice, you need to clone it? this is how DOM works, here you're referencing `childNodes`, no magic whatsoever, and no vDOM neither, so ... clone nodes you want to repeat in your template, and clone these once, for better performance on each update (same ref, no changes).

Yes got it. This solution is very short and simple.

**Comment by WebReflection** [comment]
> if I use a literal type of object how to call render function? I would like to use init function etc.

You still need to hook the render, so this an example:

```js
import { render } from '//cdn.skypack.dev/uhtml/jsx';
import { render as hooked, define, useState } from "https://unpkg.com/hooked-elements?module";

define("func-counter", {
  init() {
    console.log(this.element.localName);
    hooked(this);
  },
  render(element) {
    const [count, update] = useState(0);
    const [children] = useState([...element.childNodes]);

    render(
      element,
      <div>
        <div>{children}</div>
        <button class="large btn" onclick={() => update(count - 1)}>
          -
        </button>
        <span class="large value"> {count} </span>
        <button class="large btn" onclick={() => update(count + 1)}>
          +
        </button>
      </div>
    );
  }
});
```

**Comment by kethan** [comment]
Awesome working. Thanks. Now the only thing I need is some tiny prototypes to define attributes.
You may close this.

**Comment by kethan** [comment]
https://twitter.com/WebReflection/status/1260948278977409026. This one here. it's you. https://github.com/tc39/proposal-object-rest-spread/issues/69
